# Generated by Django 6.0.3 on 2026-03-31 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0002_genre_album_slug_artist_slug_track_slug_track_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(unique=True, verbose_name='Жанр'),
        ),
    ]
