# Generated by Django 6.0.3 on 2026-03-31 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0003_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Tracks', to='musiclibrary.artist', verbose_name='Исполнитель'),
        ),
    ]
