# Generated by Django 6.0.3 on 2026-03-31 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0004_track_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='track',
            name='disk',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер диска'),
        ),
        migrations.AddField(
            model_name='track',
            name='file_name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя файла'),
        ),
        migrations.AddField(
            model_name='track',
            name='genre_auto_detect',
            field=models.CharField(blank=True, null=True, verbose_name='Жанр автоопределение'),
        ),
        migrations.AddField(
            model_name='track',
            name='total_disks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего дисков'),
        ),
        migrations.AddField(
            model_name='track',
            name='total_tracks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Всего треков'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tracks', to='musiclibrary.album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='bitrate',
            field=models.CharField(blank=True, null=True, verbose_name='Битрейт'),
        ),
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='format',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер трека'),
        ),
    ]
