# Generated by Django 6.0.3 on 2026-03-31 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0005_track_date_track_disk_track_file_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Albums', to='musiclibrary.artist'),
        ),
    ]
