# Generated by Django 6.0.3 on 2026-03-31 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiclibrary', '0006_alter_album_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='date',
            field=models.CharField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
