# Generated by Django 6.0.3 on 2026-03-31 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_verbose_type', models.BooleanField(choices=[('стандартный', 'стандартный'), ('расширенный', 'расширенный')], default=True, verbose_name='Просмотрщик книг')),
                ('order_by', models.CharField(blank=True, max_length=200, null=True, verbose_name='Поле для сортировки')),
                ('is_reverse_order_by', models.BooleanField(blank=True, null=True, verbose_name='Прямой или обратный порядок сортировки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
