# Generated by Django 6.0.3 on 2026-03-31 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklibrary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileSettings',
        ),
    ]
