# Generated by Django 5.0.2 on 2024-02-14 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, unique=True)),
                ('author_create_time', models.DateTimeField(auto_now_add=True)),
                ('author_update_time', models.DateTimeField(auto_now=True)),
                ('author_slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category_name', models.CharField(max_length=200, unique=True)),
                ('book_category_slug', models.SlugField(max_length=255, unique=True)),
                ('book_category_create_time', models.DateTimeField(auto_now_add=True)),
                ('book_category_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_tag_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('book_tag_slug', models.SlugField(max_length=255, unique=True)),
                ('book_tag_create_time', models.DateTimeField(auto_now_add=True)),
                ('book_tag_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_genre_name', models.CharField(max_length=200, unique=200)),
                ('book_genre_slug', models.SlugField(max_length=255, unique=True)),
                ('book_genre_create_time', models.DateTimeField(auto_now_add=True)),
                ('book_genre_update_time', models.DateTimeField(auto_now=True)),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zvmediaserver.bookcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, unique=True)),
                ('book_path', models.CharField(max_length=300, unique=True)),
                ('book_slug', models.SlugField(max_length=255, unique=True)),
                ('book_create_time', models.DateTimeField(auto_now_add=True)),
                ('book_update_time', models.DateTimeField(auto_now=True)),
                ('book_author', models.ManyToManyField(related_name='book_with_author', to='zvmediaserver.author')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zvmediaserver.bookcategory')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zvmediaserver.bookgenre')),
                ('book_tag', models.ManyToManyField(blank=True, related_name='book_with_tag', to='zvmediaserver.booktag')),
            ],
            options={
                'ordering': ['-book_create_time'],
                'indexes': [models.Index(fields=['-book_create_time'], name='zvmediaserv_book_cr_2f7963_idx')],
            },
        ),
    ]
