# Generated by Django 5.0.2 on 2024-02-27 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='BookReadList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Тэг')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
        ),
        migrations.CreateModel(
            name='BookSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Подкатегория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zvmediaserver.bookcategory', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('file', models.FileField(upload_to='book', verbose_name='Файл')),
                ('status', models.CharField(choices=[('не читалась', 'не читалась'), ('в процессе', 'в процессе'), ('прочитана', 'прочитана')], default='Не читалась', max_length=200, verbose_name='Статус')),
                ('pages_count', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('words_count', models.IntegerField(blank=True, null=True, verbose_name='Количество слов')),
                ('time_to_read', models.FloatField(blank=True, null=True, verbose_name='Часов на чтение')),
                ('is_favorites', models.BooleanField(default=False, verbose_name='Избранное')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('author', models.ManyToManyField(related_name='book', to='zvmediaserver.bookauthor', verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zvmediaserver.bookcategory', verbose_name='Категория')),
                ('reading_list', models.ManyToManyField(blank=True, related_name='book', to='zvmediaserver.bookreadlist', verbose_name='Список чтения')),
                ('subcategory', models.ManyToManyField(related_name='book', to='zvmediaserver.booksubcategory', verbose_name='Подкатегория')),
                ('tag', models.ManyToManyField(blank=True, related_name='book', to='zvmediaserver.booktag', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['-create_time'], name='zvmediaserv_create__89c9b1_idx')],
            },
        ),
    ]
