# Generated by Django 5.0.2 on 2025-03-18 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zvmediaserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbookreadinglist',
            name='books_ordering',
        ),
        migrations.RemoveField(
            model_name='bookreadinglist',
            name='books_ordering',
        ),
        migrations.RemoveField(
            model_name='bookreadinglist',
            name='books',
        ),
        migrations.RemoveField(
            model_name='bookreadinglist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booktag',
            name='user',
        ),
        migrations.RemoveField(
            model_name='book',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='historicalbookorderinginreadinglist',
            name='book',
        ),
        migrations.RemoveField(
            model_name='historicalbookorderinginreadinglist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbookorderinginreadinglist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalbookreadinglist',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbookreadinglist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicalbooktag',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalbooktag',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookOrderingInReadingList',
        ),
        migrations.DeleteModel(
            name='BookReadingList',
        ),
        migrations.DeleteModel(
            name='BookTag',
        ),
        migrations.DeleteModel(
            name='HistoricalBookOrderingInReadingList',
        ),
        migrations.DeleteModel(
            name='HistoricalBookReadingList',
        ),
        migrations.DeleteModel(
            name='HistoricalBookTag',
        ),
    ]
