# Generated by Django 5.0.2 on 2024-02-14 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zvmediaserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(related_name='book', to='zvmediaserver.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zvmediaserver.bookcategory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zvmediaserver.bookgenre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_tag',
            field=models.ManyToManyField(blank=True, related_name='book', to='zvmediaserver.booktag'),
        ),
    ]
